version: '3.8'
services:
  backend-api:
    build:
      context: .
    command: 'yarn start:dev'
    ports:
      - '3010:3010'
    environment:
      - APP_PORT=3010
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=core
    volumes:
      - ./src:/app/src
